/*
  EGL-OpenGL-Stubs    EGL and OpenGL stubs
  Copyright (C) 2024  Nicolas Caramelli

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
*/

void glAccum() {}
void glActiveShaderProgram() {}
void glActiveTexture() {}
void glAlphaFunc() {}
void glAreTexturesResident() {}
void glArrayElement() {}
void glAttachShader() {}
void glBegin() {}
void glBeginConditionalRender() {}
void glBeginQuery() {}
void glBeginQueryIndexed() {}
void glBeginTransformFeedback() {}
void glBindAttribLocation() {}
void glBindBuffer() {}
void glBindBufferBase() {}
void glBindBufferRange() {}
void glBindFragDataLocation() {}
void glBindFragDataLocationIndexed() {}
void glBindFramebuffer() {}
void glBindImageTexture() {}
void glBindProgramPipeline() {}
void glBindRenderbuffer() {}
void glBindSampler() {}
void glBindTexture() {}
void glBindTransformFeedback() {}
void glBindVertexArray() {}
void glBindVertexBuffer() {}
void glBitmap() {}
void glBlendColor() {}
void glBlendEquation() {}
void glBlendEquationSeparate() {}
void glBlendEquationSeparatei() {}
void glBlendEquationi() {}
void glBlendFunc() {}
void glBlendFuncSeparate() {}
void glBlendFuncSeparatei() {}
void glBlendFunci() {}
void glBlitFramebuffer() {}
void glBufferData() {}
void glBufferSubData() {}
void glCallList() {}
void glCallLists() {}
void glCheckFramebufferStatus() {}
void glClampColor() {}
void glClear() {}
void glClearAccum() {}
void glClearBufferData() {}
void glClearBufferSubData() {}
void glClearBufferfi() {}
void glClearBufferfv() {}
void glClearBufferiv() {}
void glClearBufferuiv() {}
void glClearColor() {}
void glClearDepth() {}
void glClearDepthf() {}
void glClearIndex() {}
void glClearStencil() {}
void glClientActiveTexture() {}
void glClientWaitSync() {}
void glClipPlane() {}
void glColor3b() {}
void glColor3bv() {}
void glColor3d() {}
void glColor3dv() {}
void glColor3f() {}
void glColor3fv() {}
void glColor3i() {}
void glColor3iv() {}
void glColor3s() {}
void glColor3sv() {}
void glColor3ub() {}
void glColor3ubv() {}
void glColor3ui() {}
void glColor3uiv() {}
void glColor3us() {}
void glColor3usv() {}
void glColor4b() {}
void glColor4bv() {}
void glColor4d() {}
void glColor4dv() {}
void glColor4f() {}
void glColor4fv() {}
void glColor4i() {}
void glColor4iv() {}
void glColor4s() {}
void glColor4sv() {}
void glColor4ub() {}
void glColor4ubv() {}
void glColor4ui() {}
void glColor4uiv() {}
void glColor4us() {}
void glColor4usv() {}
void glColorMask() {}
void glColorMaski() {}
void glColorMaterial() {}
void glColorP3ui() {}
void glColorP3uiv() {}
void glColorP4ui() {}
void glColorP4uiv() {}
void glColorPointer() {}
void glCompileShader() {}
void glCompressedTexImage1D() {}
void glCompressedTexImage2D() {}
void glCompressedTexImage3D() {}
void glCompressedTexSubImage1D() {}
void glCompressedTexSubImage2D() {}
void glCompressedTexSubImage3D() {}
void glCopyBufferSubData() {}
void glCopyImageSubData() {}
void glCopyPixels() {}
void glCopyTexImage1D() {}
void glCopyTexImage2D() {}
void glCopyTexSubImage1D() {}
void glCopyTexSubImage2D() {}
void glCopyTexSubImage3D() {}
void glCreateProgram() {}
void glCreateShader() {}
void glCreateShaderProgramv() {}
void glCullFace() {}
void glDebugMessageCallback() {}
void glDebugMessageControl() {}
void glDebugMessageInsert() {}
void glDeleteBuffers() {}
void glDeleteFramebuffers() {}
void glDeleteLists() {}
void glDeleteProgram() {}
void glDeleteProgramPipelines() {}
void glDeleteQueries() {}
void glDeleteRenderbuffers() {}
void glDeleteSamplers() {}
void glDeleteShader() {}
void glDeleteSync() {}
void glDeleteTextures() {}
void glDeleteTransformFeedbacks() {}
void glDeleteVertexArrays() {}
void glDepthFunc() {}
void glDepthMask() {}
void glDepthRange() {}
void glDepthRangeArrayv() {}
void glDepthRangeIndexed() {}
void glDepthRangef() {}
void glDetachShader() {}
void glDisable() {}
void glDisableClientState() {}
void glDisableVertexAttribArray() {}
void glDisablei() {}
void glDispatchCompute() {}
void glDispatchComputeIndirect() {}
void glDrawArrays() {}
void glDrawArraysIndirect() {}
void glDrawArraysInstanced() {}
void glDrawArraysInstancedBaseInstance() {}
void glDrawBuffer() {}
void glDrawBuffers() {}
void glDrawElements() {}
void glDrawElementsBaseVertex() {}
void glDrawElementsIndirect() {}
void glDrawElementsInstanced() {}
void glDrawElementsInstancedBaseInstance() {}
void glDrawElementsInstancedBaseVertex() {}
void glDrawElementsInstancedBaseVertexBaseInstance() {}
void glDrawPixels() {}
void glDrawRangeElements() {}
void glDrawRangeElementsBaseVertex() {}
void glDrawTransformFeedback() {}
void glDrawTransformFeedbackInstanced() {}
void glDrawTransformFeedbackStream() {}
void glDrawTransformFeedbackStreamInstanced() {}
void glEdgeFlag() {}
void glEdgeFlagPointer() {}
void glEdgeFlagv() {}
void glEnable() {}
void glEnableClientState() {}
void glEnableVertexAttribArray() {}
void glEnablei() {}
void glEnd() {}
void glEndConditionalRender() {}
void glEndList() {}
void glEndQuery() {}
void glEndQueryIndexed() {}
void glEndTransformFeedback() {}
void glEvalCoord1d() {}
void glEvalCoord1dv() {}
void glEvalCoord1f() {}
void glEvalCoord1fv() {}
void glEvalCoord2d() {}
void glEvalCoord2dv() {}
void glEvalCoord2f() {}
void glEvalCoord2fv() {}
void glEvalMesh1() {}
void glEvalMesh2() {}
void glEvalPoint1() {}
void glEvalPoint2() {}
void glFBDevCreateBuffer() {}
void glFBDevCreateContext() {}
void glFBDevCreateVisual() {}
void glFBDevDestroyBuffer() {}
void glFBDevDestroyContext() {}
void glFBDevDestroyVisual() {}
void glFBDevGetBufferAttrib() {}
void glFBDevGetContextAttrib() {}
void glFBDevGetCurrentContext() {}
void glFBDevGetCurrentDrawBuffer() {}
void glFBDevGetCurrentReadBuffer() {}
void glFBDevGetProcAddress() {}
void glFBDevGetString() {}
void glFBDevGetVisualAttrib() {}
void glFBDevMakeCurrent() {}
void glFBDevSetWindow() {}
void glFBDevSwapBuffers() {}
void glFeedbackBuffer() {}
void glFenceSync() {}
void glFinish() {}
void glFlush() {}
void glFlushMappedBufferRange() {}
void glFogCoordPointer() {}
void glFogCoordd() {}
void glFogCoorddv() {}
void glFogCoordf() {}
void glFogCoordfv() {}
void glFogf() {}
void glFogfv() {}
void glFogi() {}
void glFogiv() {}
void glFramebufferParameteri() {}
void glFramebufferRenderbuffer() {}
void glFramebufferTexture() {}
void glFramebufferTexture1D() {}
void glFramebufferTexture2D() {}
void glFramebufferTexture3D() {}
void glFramebufferTextureLayer() {}
void glFrontFace() {}
void glFrustum() {}
void glGenBuffers() {}
void glGenFramebuffers() {}
void glGenLists() {}
void glGenProgramPipelines() {}
void glGenQueries() {}
void glGenRenderbuffers() {}
void glGenSamplers() {}
void glGenTextures() {}
void glGenTransformFeedbacks() {}
void glGenVertexArrays() {}
void glGenerateMipmap() {}
void glGetActiveAtomicCounterBufferiv() {}
void glGetActiveAttrib() {}
void glGetActiveSubroutineName() {}
void glGetActiveSubroutineUniformName() {}
void glGetActiveSubroutineUniformiv() {}
void glGetActiveUniform() {}
void glGetActiveUniformBlockName() {}
void glGetActiveUniformBlockiv() {}
void glGetActiveUniformName() {}
void glGetActiveUniformsiv() {}
void glGetAttachedShaders() {}
void glGetAttribLocation() {}
void glGetBooleani_v() {}
void glGetBooleanv() {}
void glGetBufferParameteri64v() {}
void glGetBufferParameteriv() {}
void glGetBufferPointerv() {}
void glGetBufferSubData() {}
void glGetClipPlane() {}
void glGetCompressedTexImage() {}
void glGetDebugMessageLog() {}
void glGetDoublei_v() {}
void glGetDoublev() {}
void glGetError() {}
void glGetFloati_v() {}
void glGetFloatv() {}
void glGetFragDataIndex() {}
void glGetFragDataLocation() {}
void glGetFramebufferAttachmentParameteriv() {}
void glGetFramebufferParameteriv() {}
void glGetInteger64i_v() {}
void glGetInteger64v() {}
void glGetIntegeri_v() {}
void glGetIntegerv() {}
void glGetInternalformati64v() {}
void glGetInternalformativ() {}
void glGetLightfv() {}
void glGetLightiv() {}
void glGetMapdv() {}
void glGetMapfv() {}
void glGetMapiv() {}
void glGetMaterialfv() {}
void glGetMaterialiv() {}
void glGetMultisamplefv() {}
void glGetObjectLabel() {}
void glGetObjectPtrLabel() {}
void glGetPixelMapfv() {}
void glGetPixelMapuiv() {}
void glGetPixelMapusv() {}
void glGetPointerv() {}
void glGetPolygonStipple() {}
void glGetProgramBinary() {}
void glGetProgramInfoLog() {}
void glGetProgramInterfaceiv() {}
void glGetProgramPipelineInfoLog() {}
void glGetProgramPipelineiv() {}
void glGetProgramResourceIndex() {}
void glGetProgramResourceLocation() {}
void glGetProgramResourceLocationIndex() {}
void glGetProgramResourceName() {}
void glGetProgramResourceiv() {}
void glGetProgramStageiv() {}
void glGetProgramiv() {}
void glGetQueryIndexediv() {}
void glGetQueryObjecti64v() {}
void glGetQueryObjectiv() {}
void glGetQueryObjectui64v() {}
void glGetQueryObjectuiv() {}
void glGetQueryiv() {}
void glGetRenderbufferParameteriv() {}
void glGetSamplerParameterIiv() {}
void glGetSamplerParameterIuiv() {}
void glGetSamplerParameterfv() {}
void glGetSamplerParameteriv() {}
void glGetShaderInfoLog() {}
void glGetShaderPrecisionFormat() {}
void glGetShaderSource() {}
void glGetShaderiv() {}
void glGetString() {}
void glGetStringi() {}
void glGetSubroutineIndex() {}
void glGetSubroutineUniformLocation() {}
void glGetSynciv() {}
void glGetTexEnvfv() {}
void glGetTexEnviv() {}
void glGetTexGendv() {}
void glGetTexGenfv() {}
void glGetTexGeniv() {}
void glGetTexImage() {}
void glGetTexLevelParameterfv() {}
void glGetTexLevelParameteriv() {}
void glGetTexParameterIiv() {}
void glGetTexParameterIuiv() {}
void glGetTexParameterfv() {}
void glGetTexParameteriv() {}
void glGetTransformFeedbackVarying() {}
void glGetUniformBlockIndex() {}
void glGetUniformIndices() {}
void glGetUniformLocation() {}
void glGetUniformSubroutineuiv() {}
void glGetUniformdv() {}
void glGetUniformfv() {}
void glGetUniformiv() {}
void glGetUniformuiv() {}
void glGetVertexAttribIiv() {}
void glGetVertexAttribIuiv() {}
void glGetVertexAttribLdv() {}
void glGetVertexAttribPointerv() {}
void glGetVertexAttribdv() {}
void glGetVertexAttribfv() {}
void glGetVertexAttribiv() {}
void glHint() {}
void glIndexMask() {}
void glIndexPointer() {}
void glIndexd() {}
void glIndexdv() {}
void glIndexf() {}
void glIndexfv() {}
void glIndexi() {}
void glIndexiv() {}
void glIndexs() {}
void glIndexsv() {}
void glIndexub() {}
void glIndexubv() {}
void glInitNames() {}
void glInterleavedArrays() {}
void glInvalidateBufferData() {}
void glInvalidateBufferSubData() {}
void glInvalidateFramebuffer() {}
void glInvalidateSubFramebuffer() {}
void glInvalidateTexImage() {}
void glInvalidateTexSubImage() {}
void glIsBuffer() {}
void glIsEnabled() {}
void glIsEnabledi() {}
void glIsFramebuffer() {}
void glIsList() {}
void glIsProgram() {}
void glIsProgramPipeline() {}
void glIsQuery() {}
void glIsRenderbuffer() {}
void glIsSampler() {}
void glIsShader() {}
void glIsSync() {}
void glIsTexture() {}
void glIsTransformFeedback() {}
void glIsVertexArray() {}
void glLightModelf() {}
void glLightModelfv() {}
void glLightModeli() {}
void glLightModeliv() {}
void glLightf() {}
void glLightfv() {}
void glLighti() {}
void glLightiv() {}
void glLineStipple() {}
void glLineWidth() {}
void glLinkProgram() {}
void glListBase() {}
void glLoadIdentity() {}
void glLoadMatrixd() {}
void glLoadMatrixf() {}
void glLoadName() {}
void glLoadTransposeMatrixd() {}
void glLoadTransposeMatrixf() {}
void glLogicOp() {}
void glMap1d() {}
void glMap1f() {}
void glMap2d() {}
void glMap2f() {}
void glMapBuffer() {}
void glMapBufferRange() {}
void glMapGrid1d() {}
void glMapGrid1f() {}
void glMapGrid2d() {}
void glMapGrid2f() {}
void glMaterialf() {}
void glMaterialfv() {}
void glMateriali() {}
void glMaterialiv() {}
void glMatrixMode() {}
void glMemoryBarrier() {}
void glMinSampleShading() {}
void glMultMatrixd() {}
void glMultMatrixf() {}
void glMultTransposeMatrixd() {}
void glMultTransposeMatrixf() {}
void glMultiDrawArrays() {}
void glMultiDrawArraysIndirect() {}
void glMultiDrawElements() {}
void glMultiDrawElementsBaseVertex() {}
void glMultiDrawElementsIndirect() {}
void glMultiTexCoord1d() {}
void glMultiTexCoord1dv() {}
void glMultiTexCoord1f() {}
void glMultiTexCoord1fv() {}
void glMultiTexCoord1i() {}
void glMultiTexCoord1iv() {}
void glMultiTexCoord1s() {}
void glMultiTexCoord1sv() {}
void glMultiTexCoord2d() {}
void glMultiTexCoord2dv() {}
void glMultiTexCoord2f() {}
void glMultiTexCoord2fv() {}
void glMultiTexCoord2i() {}
void glMultiTexCoord2iv() {}
void glMultiTexCoord2s() {}
void glMultiTexCoord2sv() {}
void glMultiTexCoord3d() {}
void glMultiTexCoord3dv() {}
void glMultiTexCoord3f() {}
void glMultiTexCoord3fv() {}
void glMultiTexCoord3i() {}
void glMultiTexCoord3iv() {}
void glMultiTexCoord3s() {}
void glMultiTexCoord3sv() {}
void glMultiTexCoord4d() {}
void glMultiTexCoord4dv() {}
void glMultiTexCoord4f() {}
void glMultiTexCoord4fv() {}
void glMultiTexCoord4i() {}
void glMultiTexCoord4iv() {}
void glMultiTexCoord4s() {}
void glMultiTexCoord4sv() {}
void glMultiTexCoordP1ui() {}
void glMultiTexCoordP1uiv() {}
void glMultiTexCoordP2ui() {}
void glMultiTexCoordP2uiv() {}
void glMultiTexCoordP3ui() {}
void glMultiTexCoordP3uiv() {}
void glMultiTexCoordP4ui() {}
void glMultiTexCoordP4uiv() {}
void glNewList() {}
void glNormal3b() {}
void glNormal3bv() {}
void glNormal3d() {}
void glNormal3dv() {}
void glNormal3f() {}
void glNormal3fv() {}
void glNormal3i() {}
void glNormal3iv() {}
void glNormal3s() {}
void glNormal3sv() {}
void glNormalP3ui() {}
void glNormalP3uiv() {}
void glNormalPointer() {}
void glObjectLabel() {}
void glObjectPtrLabel() {}
void glOrtho() {}
void glPassThrough() {}
void glPatchParameterfv() {}
void glPatchParameteri() {}
void glPauseTransformFeedback() {}
void glPixelMapfv() {}
void glPixelMapuiv() {}
void glPixelMapusv() {}
void glPixelStoref() {}
void glPixelStorei() {}
void glPixelTransferf() {}
void glPixelTransferi() {}
void glPixelZoom() {}
void glPointParameterf() {}
void glPointParameterfv() {}
void glPointParameteri() {}
void glPointParameteriv() {}
void glPointSize() {}
void glPolygonMode() {}
void glPolygonOffset() {}
void glPolygonStipple() {}
void glPopAttrib() {}
void glPopClientAttrib() {}
void glPopDebugGroup() {}
void glPopMatrix() {}
void glPopName() {}
void glPrimitiveRestartIndex() {}
void glPrioritizeTextures() {}
void glProgramBinary() {}
void glProgramParameteri() {}
void glProgramUniform1d() {}
void glProgramUniform1dv() {}
void glProgramUniform1f() {}
void glProgramUniform1fv() {}
void glProgramUniform1i() {}
void glProgramUniform1iv() {}
void glProgramUniform1ui() {}
void glProgramUniform1uiv() {}
void glProgramUniform2d() {}
void glProgramUniform2dv() {}
void glProgramUniform2f() {}
void glProgramUniform2fv() {}
void glProgramUniform2i() {}
void glProgramUniform2iv() {}
void glProgramUniform2ui() {}
void glProgramUniform2uiv() {}
void glProgramUniform3d() {}
void glProgramUniform3dv() {}
void glProgramUniform3f() {}
void glProgramUniform3fv() {}
void glProgramUniform3i() {}
void glProgramUniform3iv() {}
void glProgramUniform3ui() {}
void glProgramUniform3uiv() {}
void glProgramUniform4d() {}
void glProgramUniform4dv() {}
void glProgramUniform4f() {}
void glProgramUniform4fv() {}
void glProgramUniform4i() {}
void glProgramUniform4iv() {}
void glProgramUniform4ui() {}
void glProgramUniform4uiv() {}
void glProgramUniformMatrix2dv() {}
void glProgramUniformMatrix2fv() {}
void glProgramUniformMatrix2x3dv() {}
void glProgramUniformMatrix2x3fv() {}
void glProgramUniformMatrix2x4dv() {}
void glProgramUniformMatrix2x4fv() {}
void glProgramUniformMatrix3dv() {}
void glProgramUniformMatrix3fv() {}
void glProgramUniformMatrix3x2dv() {}
void glProgramUniformMatrix3x2fv() {}
void glProgramUniformMatrix3x4dv() {}
void glProgramUniformMatrix3x4fv() {}
void glProgramUniformMatrix4dv() {}
void glProgramUniformMatrix4fv() {}
void glProgramUniformMatrix4x2dv() {}
void glProgramUniformMatrix4x2fv() {}
void glProgramUniformMatrix4x3dv() {}
void glProgramUniformMatrix4x3fv() {}
void glProvokingVertex() {}
void glPushAttrib() {}
void glPushClientAttrib() {}
void glPushDebugGroup() {}
void glPushMatrix() {}
void glPushName() {}
void glQueryCounter() {}
void glRasterPos2d() {}
void glRasterPos2dv() {}
void glRasterPos2f() {}
void glRasterPos2fv() {}
void glRasterPos2i() {}
void glRasterPos2iv() {}
void glRasterPos2s() {}
void glRasterPos2sv() {}
void glRasterPos3d() {}
void glRasterPos3dv() {}
void glRasterPos3f() {}
void glRasterPos3fv() {}
void glRasterPos3i() {}
void glRasterPos3iv() {}
void glRasterPos3s() {}
void glRasterPos3sv() {}
void glRasterPos4d() {}
void glRasterPos4dv() {}
void glRasterPos4f() {}
void glRasterPos4fv() {}
void glRasterPos4i() {}
void glRasterPos4iv() {}
void glRasterPos4s() {}
void glRasterPos4sv() {}
void glReadBuffer() {}
void glReadPixels() {}
void glRectd() {}
void glRectdv() {}
void glRectf() {}
void glRectfv() {}
void glRecti() {}
void glRectiv() {}
void glRects() {}
void glRectsv() {}
void glReleaseShaderCompiler() {}
void glRenderMode() {}
void glRenderbufferStorage() {}
void glRenderbufferStorageMultisample() {}
void glResumeTransformFeedback() {}
void glRotated() {}
void glRotatef() {}
void glSampleCoverage() {}
void glSampleMaski() {}
void glSamplerParameterIiv() {}
void glSamplerParameterIuiv() {}
void glSamplerParameterf() {}
void glSamplerParameterfv() {}
void glSamplerParameteri() {}
void glSamplerParameteriv() {}
void glScaled() {}
void glScalef() {}
void glScissor() {}
void glScissorArrayv() {}
void glScissorIndexed() {}
void glScissorIndexedv() {}
void glSecondaryColor3b() {}
void glSecondaryColor3bv() {}
void glSecondaryColor3d() {}
void glSecondaryColor3dv() {}
void glSecondaryColor3f() {}
void glSecondaryColor3fv() {}
void glSecondaryColor3i() {}
void glSecondaryColor3iv() {}
void glSecondaryColor3s() {}
void glSecondaryColor3sv() {}
void glSecondaryColor3ub() {}
void glSecondaryColor3ubv() {}
void glSecondaryColor3ui() {}
void glSecondaryColor3uiv() {}
void glSecondaryColor3us() {}
void glSecondaryColor3usv() {}
void glSecondaryColorP3ui() {}
void glSecondaryColorP3uiv() {}
void glSecondaryColorPointer() {}
void glSelectBuffer() {}
void glShadeModel() {}
void glShaderBinary() {}
void glShaderSource() {}
void glShaderStorageBlockBinding() {}
void glStencilFunc() {}
void glStencilFuncSeparate() {}
void glStencilMask() {}
void glStencilMaskSeparate() {}
void glStencilOp() {}
void glStencilOpSeparate() {}
void glTexBuffer() {}
void glTexBufferRange() {}
void glTexCoord1d() {}
void glTexCoord1dv() {}
void glTexCoord1f() {}
void glTexCoord1fv() {}
void glTexCoord1i() {}
void glTexCoord1iv() {}
void glTexCoord1s() {}
void glTexCoord1sv() {}
void glTexCoord2d() {}
void glTexCoord2dv() {}
void glTexCoord2f() {}
void glTexCoord2fv() {}
void glTexCoord2i() {}
void glTexCoord2iv() {}
void glTexCoord2s() {}
void glTexCoord2sv() {}
void glTexCoord3d() {}
void glTexCoord3dv() {}
void glTexCoord3f() {}
void glTexCoord3fv() {}
void glTexCoord3i() {}
void glTexCoord3iv() {}
void glTexCoord3s() {}
void glTexCoord3sv() {}
void glTexCoord4d() {}
void glTexCoord4dv() {}
void glTexCoord4f() {}
void glTexCoord4fv() {}
void glTexCoord4i() {}
void glTexCoord4iv() {}
void glTexCoord4s() {}
void glTexCoord4sv() {}
void glTexCoordP1ui() {}
void glTexCoordP1uiv() {}
void glTexCoordP2ui() {}
void glTexCoordP2uiv() {}
void glTexCoordP3ui() {}
void glTexCoordP3uiv() {}
void glTexCoordP4ui() {}
void glTexCoordP4uiv() {}
void glTexCoordPointer() {}
void glTexEnvf() {}
void glTexEnvfv() {}
void glTexEnvi() {}
void glTexEnviv() {}
void glTexGend() {}
void glTexGendv() {}
void glTexGenf() {}
void glTexGenfv() {}
void glTexGeni() {}
void glTexGeniv() {}
void glTexImage1D() {}
void glTexImage2D() {}
void glTexImage2DMultisample() {}
void glTexImage3D() {}
void glTexImage3DMultisample() {}
void glTexParameterIiv() {}
void glTexParameterIuiv() {}
void glTexParameterf() {}
void glTexParameterfv() {}
void glTexParameteri() {}
void glTexParameteriv() {}
void glTexStorage1D() {}
void glTexStorage2D() {}
void glTexStorage2DMultisample() {}
void glTexStorage3D() {}
void glTexStorage3DMultisample() {}
void glTexSubImage1D() {}
void glTexSubImage2D() {}
void glTexSubImage3D() {}
void glTextureView() {}
void glTransformFeedbackVaryings() {}
void glTranslated() {}
void glTranslatef() {}
void glUniform1d() {}
void glUniform1dv() {}
void glUniform1f() {}
void glUniform1fv() {}
void glUniform1i() {}
void glUniform1iv() {}
void glUniform1ui() {}
void glUniform1uiv() {}
void glUniform2d() {}
void glUniform2dv() {}
void glUniform2f() {}
void glUniform2fv() {}
void glUniform2i() {}
void glUniform2iv() {}
void glUniform2ui() {}
void glUniform2uiv() {}
void glUniform3d() {}
void glUniform3dv() {}
void glUniform3f() {}
void glUniform3fv() {}
void glUniform3i() {}
void glUniform3iv() {}
void glUniform3ui() {}
void glUniform3uiv() {}
void glUniform4d() {}
void glUniform4dv() {}
void glUniform4f() {}
void glUniform4fv() {}
void glUniform4i() {}
void glUniform4iv() {}
void glUniform4ui() {}
void glUniform4uiv() {}
void glUniformBlockBinding() {}
void glUniformMatrix2dv() {}
void glUniformMatrix2fv() {}
void glUniformMatrix2x3dv() {}
void glUniformMatrix2x3fv() {}
void glUniformMatrix2x4dv() {}
void glUniformMatrix2x4fv() {}
void glUniformMatrix3dv() {}
void glUniformMatrix3fv() {}
void glUniformMatrix3x2dv() {}
void glUniformMatrix3x2fv() {}
void glUniformMatrix3x4dv() {}
void glUniformMatrix3x4fv() {}
void glUniformMatrix4dv() {}
void glUniformMatrix4fv() {}
void glUniformMatrix4x2dv() {}
void glUniformMatrix4x2fv() {}
void glUniformMatrix4x3dv() {}
void glUniformMatrix4x3fv() {}
void glUniformSubroutinesuiv() {}
void glUnmapBuffer() {}
void glUseProgram() {}
void glUseProgramStages() {}
void glValidateProgram() {}
void glValidateProgramPipeline() {}
void glVertex2d() {}
void glVertex2dv() {}
void glVertex2f() {}
void glVertex2fv() {}
void glVertex2i() {}
void glVertex2iv() {}
void glVertex2s() {}
void glVertex2sv() {}
void glVertex3d() {}
void glVertex3dv() {}
void glVertex3f() {}
void glVertex3fv() {}
void glVertex3i() {}
void glVertex3iv() {}
void glVertex3s() {}
void glVertex3sv() {}
void glVertex4d() {}
void glVertex4dv() {}
void glVertex4f() {}
void glVertex4fv() {}
void glVertex4i() {}
void glVertex4iv() {}
void glVertex4s() {}
void glVertex4sv() {}
void glVertexAttrib1d() {}
void glVertexAttrib1dv() {}
void glVertexAttrib1f() {}
void glVertexAttrib1fv() {}
void glVertexAttrib1s() {}
void glVertexAttrib1sv() {}
void glVertexAttrib2d() {}
void glVertexAttrib2dv() {}
void glVertexAttrib2f() {}
void glVertexAttrib2fv() {}
void glVertexAttrib2s() {}
void glVertexAttrib2sv() {}
void glVertexAttrib3d() {}
void glVertexAttrib3dv() {}
void glVertexAttrib3f() {}
void glVertexAttrib3fv() {}
void glVertexAttrib3s() {}
void glVertexAttrib3sv() {}
void glVertexAttrib4Nbv() {}
void glVertexAttrib4Niv() {}
void glVertexAttrib4Nsv() {}
void glVertexAttrib4Nub() {}
void glVertexAttrib4Nubv() {}
void glVertexAttrib4Nuiv() {}
void glVertexAttrib4Nusv() {}
void glVertexAttrib4bv() {}
void glVertexAttrib4d() {}
void glVertexAttrib4dv() {}
void glVertexAttrib4f() {}
void glVertexAttrib4fv() {}
void glVertexAttrib4iv() {}
void glVertexAttrib4s() {}
void glVertexAttrib4sv() {}
void glVertexAttrib4ubv() {}
void glVertexAttrib4uiv() {}
void glVertexAttrib4usv() {}
void glVertexAttribBinding() {}
void glVertexAttribDivisor() {}
void glVertexAttribFormat() {}
void glVertexAttribI1i() {}
void glVertexAttribI1iv() {}
void glVertexAttribI1ui() {}
void glVertexAttribI1uiv() {}
void glVertexAttribI2i() {}
void glVertexAttribI2iv() {}
void glVertexAttribI2ui() {}
void glVertexAttribI2uiv() {}
void glVertexAttribI3i() {}
void glVertexAttribI3iv() {}
void glVertexAttribI3ui() {}
void glVertexAttribI3uiv() {}
void glVertexAttribI4bv() {}
void glVertexAttribI4i() {}
void glVertexAttribI4iv() {}
void glVertexAttribI4sv() {}
void glVertexAttribI4ubv() {}
void glVertexAttribI4ui() {}
void glVertexAttribI4uiv() {}
void glVertexAttribI4usv() {}
void glVertexAttribIFormat() {}
void glVertexAttribIPointer() {}
void glVertexAttribL1d() {}
void glVertexAttribL1dv() {}
void glVertexAttribL2d() {}
void glVertexAttribL2dv() {}
void glVertexAttribL3d() {}
void glVertexAttribL3dv() {}
void glVertexAttribL4d() {}
void glVertexAttribL4dv() {}
void glVertexAttribLFormat() {}
void glVertexAttribLPointer() {}
void glVertexAttribP1ui() {}
void glVertexAttribP1uiv() {}
void glVertexAttribP2ui() {}
void glVertexAttribP2uiv() {}
void glVertexAttribP3ui() {}
void glVertexAttribP3uiv() {}
void glVertexAttribP4ui() {}
void glVertexAttribP4uiv() {}
void glVertexAttribPointer() {}
void glVertexBindingDivisor() {}
void glVertexP2ui() {}
void glVertexP2uiv() {}
void glVertexP3ui() {}
void glVertexP3uiv() {}
void glVertexP4ui() {}
void glVertexP4uiv() {}
void glVertexPointer() {}
void glViewport() {}
void glViewportArrayv() {}
void glViewportIndexedf() {}
void glViewportIndexedfv() {}
void glWaitSync() {}
void glWindowPos2d() {}
void glWindowPos2dv() {}
void glWindowPos2f() {}
void glWindowPos2fv() {}
void glWindowPos2i() {}
void glWindowPos2iv() {}
void glWindowPos2s() {}
void glWindowPos2sv() {}
void glWindowPos3d() {}
void glWindowPos3dv() {}
void glWindowPos3f() {}
void glWindowPos3fv() {}
void glWindowPos3i() {}
void glWindowPos3iv() {}
void glWindowPos3s() {}
void glWindowPos3sv() {}
void glXChooseFBConfig() {}
void glXChooseVisual() {}
void glXCopyContext() {}
void glXCreateContext() {}
void glXCreateGLXPixmap() {}
void glXCreateNewContext() {}
void glXCreatePbuffer() {}
void glXCreatePixmap() {}
void glXCreateWindow() {}
void glXDestroyContext() {}
void glXDestroyGLXPixmap() {}
void glXDestroyPbuffer() {}
void glXDestroyPixmap() {}
void glXDestroyWindow() {}
void glXGetClientString() {}
void glXGetConfig() {}
void glXGetCurrentContext() {}
void glXGetCurrentDisplay() {}
void glXGetCurrentDrawable() {}
void glXGetCurrentReadDrawable() {}
void glXGetFBConfigAttrib() {}
void glXGetFBConfigs() {}
void glXGetProcAddress() {}
void glXGetSelectedEvent() {}
void glXGetVisualFromFBConfig() {}
void glXIsDirect() {}
void glXMakeContextCurrent() {}
void glXMakeCurrent() {}
void glXQueryContext() {}
void glXQueryDrawable() {}
void glXQueryExtension() {}
void glXQueryExtensionsString() {}
void glXQueryServerString() {}
void glXQueryVersion() {}
void glXSelectEvent() {}
void glXSwapBuffers() {}
void glXUseXFont() {}
void glXWaitGL() {}
void glXWaitX() {}
